### PR TITLE
fix: type casting

### LINKED ISSUE #25: queue:work default - error after start job
CodeIgniter\CLI\CLI::print(): Argument #1 ($text) must be of type string, int given, called in \vendor\codeigniter4\queue\src\Commands\QueueWork.php on line 164

at SYSTEMPATH\CLI\CLI.php:449

Backtrace:
  1    VENDORPATH\codeigniter4\queue\src\Commands\QueueWork.php:164
       CodeIgniter\CLI\CLI::print()

  2    SYSTEMPATH\CLI\Commands.php:65
       CodeIgniter\Queue\Commands\QueueWork()->run()

  3    SYSTEMPATH\CLI\Console.php:46
       CodeIgniter\CLI\Commands()->run()

  4    ROOTPATH\spark:102
       CodeIgniter\CLI\Console()->run()

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes #25

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]

**Comment by michalsn** [comment]
Thanks!

File: src/Commands/QueueFlush.php [hunk 1]
```diff
@@ -56,6 +56,10 @@ public function run(array $params)
         $hours = $params['hours'] ?? CLI::getOption('hours');
         $queue = $params['queue'] ?? CLI::getOption('queue');
 
+        if ($hours !== null) {
+            $hours = (int) $hours;
+        }
```
Comment (MGatner) [inline src/Commands/QueueFlush.php:61]: I like the ternary you switched to below. 
```suggestion
        $hours = $hours === null ? null : (int) $hours;
```
